### ISSUE TITLE
new-ui-basemaps branch: last 3 automated tests failing (tester plugin)

### ISSUE THREAD

**Issue by gioman** [boundlessgeo/qgis-connect-plugin#13]
plugin: head from new-ui-basemaps branch
qgis: 2.18.9

```
Test name: Boundless Connect-Create the default project with authcfg
Test result:Test failed at step 'Run unit test' with message:
(<type 'exceptions.AttributeError'>, AttributeError("'module' object has no attribute 'create_default_project'",), <traceback object at 0x7f332b23c128>)
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/giovanni/.qgis2/python/plugins/boundlessconnect/tests/testerplugin.py", line 339, in test_utils_create_default_auth_project
    prj = utils.create_default_project(

Traceback (most recent call last):
  File "/home/giovanni/.qgis2/python/plugins/qgistester/testerwidget.py", line 119, in runNextStep
    execute(step.function)
  File "/home/giovanni/.qgis2/python/plugins/qgistester/utils.py", line 70, in execute
    return func()
  File "/home/giovanni/.qgis2/python/plugins/qgistester/test.py", line 66, in _runTest
    raise Exception(desc)
Exception: (<type 'exceptions.AttributeError'>, AttributeError("'module' object has no attribute 'create_default_project'",), <traceback object at 0x7f332b23c128>)
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/giovanni/.qgis2/python/plugins/boundlessconnect/tests/testerplugin.py", line 339, in test_utils_create_default_auth_project
    prj = utils.create_default_project(
```

```
Test name: Boundless Connect-Use a no_auth project template for automated testing of valid project
Test result:Test failed at step 'Run unit test' with message:
(<type 'exceptions.AttributeError'>, AttributeError("'module' object has no attribute 'create_default_project'",), <traceback object at 0x7f332b23c0e0>)
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/giovanni/.qgis2/python/plugins/boundlessconnect/tests/testerplugin.py", line 354, in test_utils_create_default_project
    prj = utils.create_default_project(

Traceback (most recent call last):
  File "/home/giovanni/.qgis2/python/plugins/qgistester/testerwidget.py", line 119, in runNextStep
    execute(step.function)
  File "/home/giovanni/.qgis2/python/plugins/qgistester/utils.py", line 70, in execute
    return func()
  File "/home/giovanni/.qgis2/python/plugins/qgistester/test.py", line 66, in _runTest
    raise Exception(desc)
Exception: (<type 'exceptions.AttributeError'>, AttributeError("'module' object has no attribute 'create_default_project'",), <traceback object at 0x7f332b23c0e0>)
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/giovanni/.qgis2/python/plugins/boundlessconnect/tests/testerplugin.py", line 354, in test_utils_create_default_project
    prj = utils.create_default_project(

```

```
Test name: Boundless Connect-Check available maps retrieval from local test json file
Test result:Test failed at step 'Run unit test' with message:
(<type 'exceptions.AttributeError'>, AttributeError("'module' object has no attribute 'get_available_maps'",), <traceback object at 0x7f332b23cb00>)
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/giovanni/.qgis2/python/plugins/boundlessconnect/tests/testerplugin.py", line 319, in test_utils_get_available_maps
    maps = utils.get_available_maps(os.path.join(self.data_dir,

Traceback (most recent call last):
  File "/home/giovanni/.qgis2/python/plugins/qgistester/testerwidget.py", line 119, in runNextStep
    execute(step.function)
  File "/home/giovanni/.qgis2/python/plugins/qgistester/utils.py", line 70, in execute
    return func()
  File "/home/giovanni/.qgis2/python/plugins/qgistester/test.py", line 66, in _runTest
    raise Exception(desc)
Exception: (<type 'exceptions.AttributeError'>, AttributeError("'module' object has no attribute 'get_available_maps'",), <traceback object at 0x7f332b23cb00>)
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/giovanni/.qgis2/python/plugins/boundlessconnect/tests/testerplugin.py", line 319, in test_utils_get_available_maps
    maps = utils.get_available_maps(os.path.join(self.data_dir,


```

**Comment by alexbruy** [comment]
This is because testing started before development phase was finished.

**Comment by alexbruy** [comment]
should be fixed
