### ISSUE TITLE
new-ui-basemaps branch: python error when clicking on "ADD TO DEFAULT PROJECT"

### ISSUE THREAD

**Issue by gioman** [boundlessgeo/qgis-connect-plugin#19]
Clean project, logged in with testing credential "enterprise", searched for mapbox maps.

```
An error has occurred while executing Python code: 

NameError: global name 'authId' is not defined 
Traceback (most recent call last):
  File "/home/giovanni/.qgis2/python/plugins/boundlessconnect/gui/connectdockwidget.py", line 185, in linkClicked
    content.addToDefaultProject(self.roles)
  File "/home/giovanni/.qgis2/python/plugins/boundlessconnect/connect.py", line 317, in addToDefaultProject
    if not basemaputils.createOrAddDefaultBasemap([self.json], [self.name], authId):
  File "/home/giovanni/.qgis2/python/plugins/boundlessconnect/basemaputils.py", line 230, in createOrAddDefaultBasemap
    prj = createDefaultProject(maps, visibleMaps, template, authcfg)
  File "/home/giovanni/.qgis2/python/plugins/boundlessconnect/basemaputils.py", line 188, in createDefaultProject
    authcfg=authId), m['name'], "wms")
NameError: global name 'authId' is not defined
```

**Comment by alexbruy** [comment]
Should be fixed
