### ISSUE TITLE
manual test "Test updating core Connect plugin via Plugin Manager" python error

### ISSUE THREAD

**Issue by gioman** [boundlessgeo/qgis-connect-plugin#2]
```
Test name: Boundless Connect-Test updating core Connect plugin via Plugin Manager
Test result:Test failed at step 'Downgrade installed Connect plugin' with message:
Traceback (most recent call last):
  File "C:/Users/qgis/.qgis2/python/plugins\qgistester\testerwidget.py", line 138, in runNextStep
    execute(step.function)
  File "C:/Users/qgis/.qgis2/python/plugins\qgistester\utils.py", line 61, in execute
    return func()
  File "C:/Users/qgis/.qgis2/python/plugins\boundlessconnect\tests\testerplugin.py", line 66, in <lambda>
    coreConnectUpdateTest.addStep('Downgrade installed Connect plugin', lambda: _downgradePlugin('boundlessconnect'))
  File "C:/Users/qgis/.qgis2/python/plugins\boundlessconnect\tests\testerplugin.py", line 196, in _downgradePlugin
    with open(metadataPath, 'wb') as f:
IOError: [Errno 13] Permission denied: u'C:/PROGRA~1/BOUNDL~1/Desktop/osgeo4w/apps/qgis/.\\python\\plugins\\boundlessconnect\\metadata.txt'
```

**Comment by alexbruy** [comment]
Test failed as it needs elevated access rights to modify plugins `metadat.txt` on the system drive. After discussion with @volaya we decided to remove it from test suite
