### ISSUE TITLE
Uncaught ImportError: No module named oauth2


### ISSUE THREAD

**Issue by dustinturp** [boundlessgeo/qgis-connect-plugin#30]
Couldn't load plugin boundlessconnect due to an error when calling its classFactory() method
Steps to reproduce
Edited from report tool (7.13.17)
 1. First Open QGIS for Boundless Desktop 1.1
 2. Second Click the remove from doc button to the left of the close window button of the Connect Plugin.
 3. Third QGIS crashes. 

**Fixed by removing Files in Libraries all QGIS and boundless files then restarting QGIS.**

```
Traceback (most recent call last):
  File "/Library/Boundless/Desktop/1.1/Cellar/qgis2-bdesk/2.18.10/QGIS for Boundless Desktop 1.1.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 333, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/Library/Boundless/Desktop/1.1/Cellar/qgis2-bdesk/2.18.10/QGIS for Boundless Desktop 1.1.app/Contents/MacOS/../Resources/python/plugins/boundlessconnect/__init__.py", line 29, in classFactory
    from boundlessconnect.boundlessconnect_plugin import BoundlessConnectPlugin
  File "/Library/Boundless/Desktop/1.1/Cellar/qgis2-bdesk/2.18.10/QGIS for Boundless Desktop 1.1.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Library/Boundless/Desktop/1.1/Cellar/qgis2-bdesk/2.18.10/QGIS for Boundless Desktop 1.1.app/Contents/MacOS/../Resources/python/plugins/boundlessconnect/boundlessconnect_plugin.py", line 47, in <module>
    from boundlessconnect.gui.connectdockwidget import getConnectDockWidget
  File "/Library/Boundless/Desktop/1.1/Cellar/qgis2-bdesk/2.18.10/QGIS for Boundless Desktop 1.1.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Library/Boundless/Desktop/1.1/Cellar/qgis2-bdesk/2.18.10/QGIS for Boundless Desktop 1.1.app/Contents/MacOS/../Resources/python/plugins/boundlessconnect/gui/connectdockwidget.py", line 50, in <module>
    from qgiscommons.oauth2 import (oauth2_supported,
  File "/Library/Boundless/Desktop/1.1/Cellar/qgis2-bdesk/2.18.10/QGIS for Boundless Desktop 1.1.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: No module named oauth2

```
boundlessconnect 1.1.0, QGIS 2.18.10 on Darwin 16.6.0

**Comment by gioman** [comment]
@dustinturp is this still valid?

**Comment by alexbruy** [comment]
Should be fixed with new qgiscommons package. Reopen if necessary
